## all paths are relative to .exe file

logo_path = "..\..\..\../Editor/res/logo/logo.png"

projects:
	porj="PeProjTest","C:\dev\__test_env/PeProjTest"
end

paths:
	py_path="..\..\..\../Editor/src/pyutils"
	py_path="..\..\..\../Editor/src/core/cli/proj_init"
	py_path="..\..\..\../Editor/src/core/cli"
	py_path="..\..\..\../Editor/src/windows"
end

fonts:
	programming = "..\..\..\../Editor/res/fonts/ProFont/ProFontWindows.ttf","1"
end

file_format_icons:
	dir_close="..\..\..\../Editor/res/icons/file_format/dir_closed.png"
	dir_open="..\..\..\../Editor/res/icons/file_format/dir_open.png"
	file_unknown="..\..\..\../Editor/res/icons/file_format/file_unknown.png"
	file_peproj="..\..\..\../Editor/res/icons/file_format/file_peproj.png"
	file_text="..\..\..\../Editor/res/icons/file_format/file_text.png"
	file_xml="..\..\..\../Editor/res/icons/file_format/file_xml.png"
	file_py="..\..\..\../Editor/res/icons/file_format/file_py.png"
	file_pyc="..\..\..\../Editor/res/icons/file_format/file_pyc.png"
	file_cpp="..\..\..\../Editor/res/icons/file_format/file_cpp.png"
	file_h="..\..\..\../Editor/res/icons/file_format/file_h.png"
	file_hpp="..\..\..\../Editor/res/icons/file_format/file_hpp.png"
	file_png="..\..\..\../Editor/res/icons/file_format/file_png.png"
	file_ttf="..\..\..\../Editor/res/icons/file_format/file_ttf.png"
	file_bin="..\..\..\../Editor/res/icons/file_format/file_bin.png"
	file_dll="..\..\..\../Editor/res/icons/file_format/file_dll.png"
	file_obj="..\..\..\../Editor/res/icons/file_format/file_obj.png"
	assets_file="..\..\..\../Editor/res/icons/file_format/assets_file.png"
	asset_texture="..\..\..\../Editor/res/icons/file_format/asset_texture.png"
	asset_font="..\..\..\../Editor/res/icons/file_format/asset_font.png"
end

menu_icons:
	none="..\..\..\../Editor/res/icons/menu_icons/none.png"
	rename="..\..\..\../Editor/res/icons/menu_icons/rename.png"
	delete="..\..\..\../Editor/res/icons/menu_icons/delete.png"
	open_in_explorer="..\..\..\../Editor/res/icons/menu_icons/open_in_explorer.png"
	new_object="..\..\..\../Editor/res/icons/menu_icons/new_obj.png"
	new_script="..\..\..\../Editor/res/icons/menu_icons/new_script.png"
end

other_icons:
	error="..\..\..\../Editor/res/icons/other_icons/error.png"
	warning="..\..\..\../Editor/res/icons/other_icons/warning.png"
	explorer_up="..\..\..\../Editor/res/icons/other_icons/explorer_up.png"
	explorer_refresh="..\..\..\../Editor/res/icons/other_icons/explorer_refresh.png"
	create_new="..\..\..\../Editor/res/icons/other_icons/create_new.png"
end