#!python
import os, subprocess
Import('env')

# os env
env_os = env.Clone()

# source files
Export('env_os')
env_os.sources = []

if env_os['platform'] == "osx":
	#SConscript('osx/SConstruct')
	pass # TODO:
elif env_os['platform'] == 'linux':
	SConscript('linux/SConstruct')
	pass
elif env_os['platform'] == "windows":
	SConscript('windows/SConstruct')
	pass

# make library
lib = env_os.StaticLibrary('bin/os', env_os.sources)
env.Prepend(LIBS=[lib])